### PR TITLE
Fixes #23 : [Misc] Python : 2.7 backward compatibility

### LINKED ISSUE #23: [Misc] Python : 2.7 backward compatibility
The SDK has been made for python 3.

But some projects are still using python 2.7 and the SDK is not backward compatible.

### PR DESCRIPTION
**Pull request by tikismoke**
This make the sdk works on python 2.7

Do not know about 3.+

Also not know how to make it works on all python version :-1:

### CODE REVIEW

**Comment by tikismoke** [comment]
Have a try on python 3 to see and let me know.

**Comment by qk7b** [comment]
I managed to do that with some unit test.
I'll but it needs more than that.

Here is the thing if you want to update your PR (and also rebase it on `develop`).

At the begining of `sdk.py`

``` python
try:
    import urllib.parse as url_parser
except ImportError:
    from urlparse import urlparse as url_parser
```

And replace all the `urlib.urlencode` by a `url_parser.urlencode`

Let me know if you update the PR or if I do this by myself.

Also I need to push some unit test to make it easier to work on with virtualenvs.

**Comment by tikismoke** [comment]
Ok let me try on my host and i'll update it ;)

Le 14 septembre 2016 18:53:32 GMT+02:00, Quentin Klein notifications@github.com a écrit :

> I managed to do that with some unit test.
> I'll but it needs more than that.
> 
> Here is the thing if you want to update your PR (and also rebase it on
> `develop`).
> 
> At the begining of `sdk.py`
> 
> ``` python
> try:
>    import urllib.parse as url_parser
> except ImportError:
>    from urlparse import urlparse as url_parser
> ```
> 
> And replace all the `urlib.urlencode` by a `url_parser.urlencode`
> 
> Let me know if you update the PR or if I do this by myself.
> 
> Also I need to push some unit test to make it easier to work on with
> virtualenvs.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/quentin7b/xee-sdk-python/pull/17#issuecomment-247079623

## 

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by qk7b** [comment]
As I just merged master into develop to keep it up to date, this will need a rebase on develop

**Comment by tikismoke** [comment]
Ok have a try on python3, for me it's ok on 2.7.3

**Comment by qk7b** [comment]
Fixes #23

**Pull request merged**
